version: '3'
services:
  db:
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
     - "dbdata:/var/lib/postgresql/data"
  
  web:
    build: '.'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    volumes:
      - '.:/app'

  js:
    build: 
      context: '.'
    tty: true    
    volumes:
      - '.:/app'
    command: 'yarn build --watch'

  css:
    build: 
      context: '.'
    tty: true    
    volumes:
      - '.:/app'
    command: 'yarn watch:css'

volumes:
  dbdata:
